<h2><center>Tugas 3 Data Mining 2019/2020</center></h2>

<center><font color="red">Deadline: 17 October 2019, 22:00WIB</font><center>

---





<h4>Nama    : Muhammad Yudistira Hanifmuti </h4>
<h4>NPM     : 1606829560 </h4>

<b>Petunjuk umum:</b>
1. Dataset yang digunakan pada tugas ini merupakan dataset diabetes yang dapat diunduh di https://bit.ly/2M5vioB
2. Deskripsi atribut pada dataset dapat dilihat pada halaman tersebut.
3. Lakukan pengolahan data dan perhitungan menggunakan bahasa pemrograman 4. Python. Gunakan template Jupyter notebook yang telah disediakan untuk menjawab soal.
4. Penggunaan Library dibatasi hanya untuk penggunaan numpy array. 
5. Format penulisan nama file di Jupyter notebook: T3_Nama_NIM.ipynb
Kumpulkan pada slot yang disediakan di scele. Deadline:.
6. Jika dalam menyelesaikan tugas ini anda berkolaborasi dengan orang lain, silahkan dituliskan dengan siapa anda berkolaborasi (pada baris ini)!



<b>K-Nearest Neighbor (KNN) (total - poin)</b>

1. <b>[- poin]</b> Lakukan range normalization pada dataset diabetes.
 
2. <b>[- poin]</b> Hitung distance matrix dari dataset dengan menggunakan :

    a. Manhattan distance
    
    b. Euclidean distance
    
    c. Cosine distance
    
2. <b>[- poin]</b> Pilihlah 10 data secara acak dari dataset, lakukan proses K-NN untuk menentukan kelas dari data tersebut dengan nilai K = 3, 5, dan 7. Untuk setiap nilai K, bandingkan hasil klasifikasi dengan menggunakan ukuran jarak Manhattan distance, Euclidean distance, dan Cosine distance. Apakah ada perbedaan ? Lakukan analisis singkat

Jawaban :

1.

In [1]:
import numpy as np
import os
import requests

# Dataset metadata
dataset_url = "https://drive.google.com/uc?authuser=0&id=1uxN2XunIHEhtv03dHgM9gE_J8i4QvKzU&export=download"
filename = 'diabetes.csv'
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Function

def load_dataset():
    ## Download and write diabetes data
    if not (os.path.exists(filename)):
        r = requests.get(dataset_url, allow_redirects=True)
        open(filename, 'wb').write(r.content)
    
    ## Read diabetes data
    dataset = np.genfromtxt(filename, delimiter=',', skip_header=1)
    return dataset

def min_over_cols(data):
    return [data[:,i].min() for i in range(data.shape[1])]

def max_over_cols(data):
    return [data[:,i].max() for i in range(data.shape[1])]

def range_normalization(data):
    ## Compute range
    min_vals = min_over_cols(data)
    max_vals = max_over_cols(data)
    range_r = [max_vals[i]-min_vals[i] for i in range(data.shape[1])]
    
    ## Compute normalization
    return (data - min_vals)/range_r
    
# Load dataset, then normalize
dataset = load_dataset()
normalized = range_normalization(dataset)

print("Dataset yang sudah dikenakan range normalization memiliki hasil akhir sebagai berikut.")
print("a. Nilai minimum sama dengan 0")
print(min_over_cols(normalized))
print("b. Nilai maksimum sama dengan 1")
print(max_over_cols(normalized))

Dataset yang sudah dikenakan range normalization memiliki hasil akhir sebagai berikut.
a. Nilai minimum sama dengan 0
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
b. Nilai maksimum sama dengan 1
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


2.

In [2]:
# Separate target from data
X, y = normalized[:, :-1], normalized[:, -1]

# Function
def manhattan_distance(v, w):
    return np.sum(np.absolute(v-w))

def euclidean_distance(v, w):
    return np.sqrt(np.sum(np.power(v-w, 2)))

def cosine_distance(v, w):
    ## norm 2 function
    def norm(v):
        return np.sqrt(np.sum(np.power(v, 2)))
    return 1 - (np.dot(v, w)/(norm(v)*norm(w)))

def distance_matrix(data, distance_type='euclidean'):
    ## Check used distance type
    if distance_type == 'euclidean':
        distance_fun = euclidean_distance
    elif distance_type == 'manhattan':
        distance_fun = manhattan_distance
    elif distance_type == 'cosine':
        distance_fun = cosine_distance
    else:
        raise ValueError('Distance type is not recognized.')
    
    ## Compute distance
    data_length = data.shape[0]
    mat = np.array([np.array([distance_fun(data[i], data[j]) for j in range(data_length)]) for i in range(data_length)])
    return mat

distance_1 = distance_matrix(X, distance_type='manhattan')
distance_2 = distance_matrix(X, distance_type='euclidean')
distance_3 = distance_matrix(X, distance_type='cosine')

print("Berikut ini adalah hasil perhitungan distance matrix menggunakan beberapa jenis distance.")
print()
print("a. Manhattan Distance")
print(distance_1)
print()
print("b. Euclidean Distance")
print(distance_2)
print()
print("c. Cosine Similarity/Distance")
print(distance_3)

Berikut ini adalah hasil perhitungan distance matrix menggunakan beberapa jenis distance.

a. Manhattan Distance
[[0.         1.25932352 1.18535216 ... 1.0548267  1.07742934 1.25820653]
 [1.25932352 0.         1.41645909 ... 0.72626112 0.86782136 0.29852661]
 [1.18535216 1.41645909 0.         ... 1.1771883  1.22024134 1.63458369]
 ...
 [1.0548267  0.72626112 1.1771883  ... 0.         1.10935337 0.81473566]
 [1.07742934 0.86782136 1.22024134 ... 1.10935337 0.         0.97991612]
 [1.25820653 0.29852661 1.63458369 ... 0.81473566 0.97991612 0.        ]]

b. Euclidean Distance
[[0.         0.56380025 0.53665043 ... 0.45162548 0.50269284 0.62234648]
 [0.56380025 0.         0.7208524  ... 0.33774235 0.45222484 0.15595016]
 [0.53665043 0.7208524  0.         ... 0.4901339  0.58690672 0.72903545]
 ...
 [0.45162548 0.33774235 0.4901339  ... 0.         0.47201476 0.34337787]
 [0.50269284 0.45222484 0.58690672 ... 0.47201476 0.         0.5408326 ]
 [0.62234648 0.15595016 0.72903545 ... 0.34337787 

3.

In [3]:
# Classification routine
def routine(X, y):
    ## Random sampling 10 data
    np.random.seed(42)
    idx = np.random.choice(X.shape[0], 10)
    X_test = X[idx]
    y_test = y[idx]
    
    ## knn process
    def do_knn(distance_matrix, k=3):
        k_nearest_idx = np.argsort(distance_matrix[idx])[:,:k]
        k_nearest_target = np.array(list(map(lambda x: y[x], k_nearest_idx)))
        test_target = np.array(list(map(lambda x: np.bincount(x.astype(int)).argmax(), k_nearest_target)))
        return test_target
    
    ## count wrong prediction
    def wrong_pred(pred, test):
        diff = abs(pred - test)
        return np.sum(np.array(list(map(lambda x: 1 if x > 0 else 0, diff))))
    
    ## Calculate distance matrix
    distance_1 = distance_matrix(X, distance_type='manhattan')
    distance_2 = distance_matrix(X, distance_type='euclidean')
    distance_3 = distance_matrix(X, distance_type='cosine')
    
    print("Data yang terpilih adalah data dengan index", idx)
    print("Target yang benar dari data terpilih adalah", y_test)
    print("Di bawah ini adalah hasil klasifikasi untuk setiap konfigurasi.")
    print()
    
    ## Do knn
    k_vals = [3, 5, 7]
    for i,k in enumerate(k_vals):
        print(i+1, "k =", k)
        
        print(" a) Manhattan distance")
        result = do_knn(distance_1, k=k)
        print("    Hasil klasifikasi adalah", result)
        print("    Prediksi yang salah sejumlah", wrong_pred(result, y_test), "data")
        print()
        print(" b) Euclidean distance")
        result = do_knn(distance_2, k=k)
        print("    Hasil klasifikasi adalah", result)
        print("    Prediksi yang salah sejumlah", wrong_pred(result, y_test), "data")
        print()
        print(" c) Cosine distance")
        result = do_knn(distance_3, k=k)
        print("    Hasil klasifikasi adalah", result)
        print("    Prediksi yang salah sejumlah", wrong_pred(result, y_test), "data")
        print()


routine(X, y)

analisis = """
Dapat dilihat bahwa KNN sudah cukup berhasil melakukan klasifikasi dengan rata-rata kesalahan prediksi hanya 1 data.
Untuk setiap nilai k, manhattan distance memiliki kesalahan yang lebih banyak bila dibandingkan dengan distance
yang lain sehingga dapat dikatakan bahwa untuk data diabetes ini manhattan distance kurang tepat untuk digunakan.
Untuk pemilihan nilai k, dapat dilihat bahwa secara umum k = 7 memiliki kesalahan prediksi lebih sedikit.
"""
print()
print(analisis)

Data yang terpilih adalah data dengan index [102 435 270 106  71 700  20 614 121 466]
Target yang benar dari data terpilih adalah [0. 1. 1. 0. 0. 0. 0. 1. 0. 0.]
Di bawah ini adalah hasil klasifikasi untuk setiap konfigurasi.

1 k = 3
 a) Manhattan distance
    Hasil klasifikasi adalah [0 1 1 0 1 0 0 1 0 0]
    Prediksi yang salah sejumlah 1 data

 b) Euclidean distance
    Hasil klasifikasi adalah [0 1 1 0 0 0 1 1 0 0]
    Prediksi yang salah sejumlah 1 data

 c) Cosine distance
    Hasil klasifikasi adalah [0 1 1 0 1 0 0 1 0 0]
    Prediksi yang salah sejumlah 1 data

2 k = 5
 a) Manhattan distance
    Hasil klasifikasi adalah [0 1 1 0 1 0 1 1 0 0]
    Prediksi yang salah sejumlah 2 data

 b) Euclidean distance
    Hasil klasifikasi adalah [0 1 1 0 0 0 1 1 0 0]
    Prediksi yang salah sejumlah 1 data

 c) Cosine distance
    Hasil klasifikasi adalah [0 1 1 0 1 0 0 1 0 0]
    Prediksi yang salah sejumlah 1 data

3 k = 7
 a) Manhattan distance
    Hasil klasifikasi adalah [0 1 1 0 1 0 

<b>Naive Bayes (total - poin)</b>

1. <b>[- poin]</b>  Lakukan klasifikasi pada dataset diabetes yang telah dinormalisasi menggunakan algoritma Naive Bayes. Proporsi pembagian data training dan testing adalah 80:20.
2. <b>[- poin]</b> Hitung hasil akurasi.
$$accuracy = \frac{number \:of \:true \:predictions}{number \:of \:total \:predictions}$$ 
3. <b>[- poin]</b> Carilah correlation coefficient untuk setiap pasang fitur pada dataset diabetes yang telah dinormalisasi.
4. <b>[- poin]</b> Hapus fitur-fitur yang saling berkorelasi, lalu lakukan kembali klasifikasi menggunakan algoritma Naive Bayes menggunakan fitur yang tersisa. Bandingkan hasil klasifikasi untuk data train dan data test (menggunakan hasil soal no.2) dari dua skenario tersebut dan berikan analisis mengenai hasil yang diperoleh.

1.

In [4]:
# Naive Bayes Classifier
class GaussianNB:
    
    def __init__(self):
        pass
        
    def fit(self, X, y):
        # Get data information
        self.classes = np.unique(y)
        self.n_classes = self.classes.shape[0]
        self.n_features = X.shape[1]
        
        # Initialize nb parameter
        self.prior = np.zeros(self.n_classes)
        self.mean = np.zeros((self.n_classes, self.n_features))
        self.variance = np.zeros((self.n_classes, self.n_features))
        
        # Compute parameter
        for i in range(self.n_classes):
            ## Get class data
            cls = self.classes[i]
            idx = y == cls
            D_i = X[idx]
            n_rows = D_i.shape[0]
            
            ## Compute class-specific parameter
            
            self.prior[i] = n_rows/X.shape[0]
            self.mean[i] = np.sum(D_i, axis=0)/n_rows
            
            ### Compute attribute variance
            centered_D = D_i - self.mean[i]
            for j in range(self.n_features):
                v = centered_D[:, j]
                self.variance[i, j] = np.dot(v, v)/n_rows
        return X
    
    def _predict_row(self, x):
        # Likelihood function
        def likelihood(x, mean, variance):
            exponent = np.exp(-(np.power(x-mean, 2)/(2*variance)))
            return (exponent/(np.sqrt(2*np.pi)*np.sqrt(self.variance[i, j])))
            
        # Initialize probability for each class
        prob = np.zeros(self.n_classes)
        
        # Compute likelihood
        for i in range(self.n_classes):
            prior = self.prior[i]
            
            likelihood = 1
            for j in range(self.n_features):
                exponent = np.exp(-(np.power(x[j]-self.mean[i, j], 2)/(2*self.variance[i, j])))
                likelihood *= (exponent/(np.sqrt(2*np.pi)*np.sqrt(self.variance[i, j])))
            prob[i] = prior * likelihood
        
        # Return argmax
        return self.classes[np.argmax(prob)]
    
    def predict(self, X):
        return np.array([self._predict_row(x) for x in X])

# Split datasetfan
split_point = int(X.shape[0]*0.8)
X, y = normalized[:, :-1], normalized[:, -1]
X_train, X_test = X[:split_point], X[split_point:]
y_train, y_test = y[:split_point], y[split_point:]

nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred = nb.predict(X_test)
print("Hasil prediksi Naive Bayes untuk 20% data test adalah sebagai berikut.")
print(y_pred)

Hasil prediksi Naive Bayes untuk 20% data test adalah sebagai berikut.
[1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1.
 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 1. 0. 1. 0. 1. 0. 0. 0. 0.]


2.

In [5]:
# accuracy score
def accuracy_score(pred, target):
    true_pred = np.sum(pred == target)
    return true_pred/pred.shape[0]

print("Hasil akurasi dari prediksi Naive Bayes adalah", accuracy_score(y_pred, y_test))

Hasil akurasi dari prediksi Naive Bayes adalah 0.7467532467532467


3.

In [6]:
# Compute corrcoef
corrcoef = np.corrcoef(normalized.T)

print("Correlation coefficient untuk setiap pasang fitur pada dataset adalah sebagai berikut.")

for i in range(corrcoef.shape[0]):
    for j in range(i, corrcoef.shape[1]):
        if i != j and j != 8:
            print("Fitur", columns[i], "("+str(i+1)+")", "dengan", columns[j], "("+str(j+1)+")",)
            print(corrcoef[i, j])
            print()

Correlation coefficient untuk setiap pasang fitur pada dataset adalah sebagai berikut.
Fitur Pregnancies (1) dengan Glucose (2)
0.12945867149927248

Fitur Pregnancies (1) dengan BloodPressure (3)
0.14128197740713994

Fitur Pregnancies (1) dengan SkinThickness (4)
-0.08167177444900722

Fitur Pregnancies (1) dengan Insulin (5)
-0.0735346143516281

Fitur Pregnancies (1) dengan BMI (6)
0.017683090727830593

Fitur Pregnancies (1) dengan DiabetesPedigreeFunction (7)
-0.03352267296261312

Fitur Pregnancies (1) dengan Age (8)
0.5443412284023389

Fitur Glucose (2) dengan BloodPressure (3)
0.15258958656866448

Fitur Glucose (2) dengan SkinThickness (4)
0.05732789073817704

Fitur Glucose (2) dengan Insulin (5)
0.3313571099202091

Fitur Glucose (2) dengan BMI (6)
0.22107106945898297

Fitur Glucose (2) dengan DiabetesPedigreeFunction (7)
0.1373372998283707

Fitur Glucose (2) dengan Age (8)
0.2635143198243335

Fitur BloodPressure (3) dengan SkinThickness (4)
0.2073705384030709

Fitur BloodPressure (

4.

In [8]:
dropped = normalized[:, [0, 1, 2, 3, 4, 5, 6, 8]]
new_X, new_y = dropped[:, :-1], dropped[:, -1]
X_train, X_test = new_X[:split_point], new_X[split_point:]
y_train, y_test = new_y[:split_point], new_y[split_point:]

nb = GaussianNB()
nb.fit(X_train,y_train)
y_pred = nb.predict(X_test)
print("Hasil akurasi dari prediksi Naive Bayes adalah", accuracy_score(y_pred, y_test))
print()

analisis = """
Hasil akurasi pada skenario kedua setelah dihapus sebagian kolom lebih tinggi ketimbang sebelum dihapus.
Dua fitur yang memiliki koefisien korelasi yang tinggi dapat berpotensi menjadi data yang redundan sehingga
classifier berpotensi mempelajari data yang salah. Namun, pada kasus ini penghapusan kolom tersebut tidak terlalu
signifikan karena nilai koefisien korelasi dari fitur tersebut tidak cukup tinggi untuk dikatakan berkorelasi.
"""
print(analisis)

Hasil akurasi dari prediksi Naive Bayes adalah 0.7532467532467533


Hasil akurasi pada skenario kedua setelah dihapus sebagian kolom lebih tinggi ketimbang sebelum dihapus.
Dua fitur yang memiliki koefisien korelasi yang tinggi dapat berpotensi menjadi data yang redundan sehingga
classifier berpotensi mempelajari data yang salah. Namun, pada kasus ini penghapusan kolom tersebut tidak terlalu
signifikan karena nilai koefisien korelasi dari fitur tersebut tidak cukup tinggi untuk dikatakan berkorelasi.

